language: rust
rust: nightly
cache: cargo
before_deploy: |
    cargo +nightly doc --no-deps \
    && echo '<meta http-equiv=refresh content=0;url=webgl_rs/index.html>' > target/doc/index.html
deploy:  
  provider: pages
  local-dir: target/doc
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: true
  on:
    branch: master